movie_store/movie/urls.py
from django.urls import path, include , re_path
from . import views

app_name = 'movie'

urlpatterns = [
  # /movies/
  re_path(r'^$',views.index,name = 'index'),

  # /movies/785/
  re_path(r'^(?P<movie_id>[0-9]+)/$', views.detail, name='detail'),

  # /movies/785/favourite/
  re_path(r'^(?P<movie_id>[0-9]+)/favourite/$', views.favourite, name='favourite'),

]

movie_store/movie_store/urls.py
from django.contrib import admin
from django.urls import path, include,re_path

urlpatterns = [
    path('admin/', admin.site.urls),
    #/movies/
    path('movies/', include('movie.urls')),
    re_path(r'^', include('movie.urls')),
]

movie_store/movie/models.py
from django.db import models
from sqlalchemy.sql.functions import mode


class Director(models.Model):
    director_name = models.CharField(max_length=250)
    age = models.IntegerField()
    picture = models.CharField(max_length=250)

    def __str__(self):
        return self.director_name


class Genres(models.Model):
    genres_category = models.CharField(max_length=250)
    is_favourite = models.BooleanField(default=False)

    def __str__(self):
        return self.genres_category


class Movies(models.Model):

    movie_name = models.CharField(max_length=250)
    year = models.IntegerField()
    duration = models.CharField(max_length=250)
    ratings = models.IntegerField()
    language = models.CharField(max_length=250)
    director = models.ForeignKey(Director, on_delete=models.CASCADE)
    genres = models.ManyToManyField(Genres)
    poster = models.CharField(max_length=1000)
    is_favourite = models.BooleanField(default=False )

    def __str__(self):
        return self.movie_name

movie_store/movie/views.py
#from django.http import HttpResponse
from builtins import KeyError

from .models import Movies,Director,Genres
#from django.template import loader
from django.shortcuts import render ,get_object_or_404
from django.http import Http404

def index(request):

    All_Movies = Movies.objects.all()

    return render(request,'movie/index.html',{'All_Movies':All_Movies})




def detail(request, movie_id):

    movie = get_object_or_404(Movies,pk=movie_id)

    return render(request, 'movie/detail.html', {'movie': movie})




def favourite(request, movie_id):

    movie = get_object_or_404(Movies,pk=movie_id)
    try:
        selected_song = movie.genres.get(pk =request.POST['genres'])
    except(KeyError, Genres.DoesNotExist):
        return render(request, 'movie/detail.html', {
            'movie': movie,
            'error_message': "you did not select a right genres"


        })
    else:
        selected_song.is_favourite= True
        selected_song.save()
        return render(request, 'movie/detail.html', {'movie': movie})

movie_store/movie/templates/movie/detail.html
<h1> hear is the details of the {{ movie.movie_name }} movie </h1>

<img src="{{ movie.poster}}">

<h2>{{ movie.movie_name }}</h2>
<h2> director is :{{ movie.director }}</h2>

<h3>{{ movie.ratings }}</h3>

<!--

    <ul>
        {%  for genres in movie.genres.all %}
            <li> {{ genres.genres_category }} </li>
        {% endfor %}


    </ul>




-->


{% if error_message %}
<p> <strong >{{error_message}}</strong></p>

{% endif %}

<form action="{% url 'movie:favourite' movie.id %}" method="post"  >
    {% csrf_token %}
    {% for genres in movie.genres.all %}
        <input type="radio"  id="genres{{ forloop.counter }}" name="genres" value="{{ genres.id }}"/>
        <label for="genres{{forloop.counter}}" >
            {{genres.genres_category}}
            {% if genres.is_favourite  %}
                <img src="https://upload.wikimedia.org/wikipedia/commons/f/f6/Choice_toxicity_icon.png"/>


            {% endif %}

        </label><br>
    {% endfor %}
    <input type="submit" value="submit" >
</form>

movie_store/movie/templates/movie/index.html
{% if All_Movies %}

    <h1>Hear are my all movies</h1>

    <ul>
        {% for movies in All_Movies %}
        <li><a href="{% url 'movie:detail' movies.id %}">{{movies.movie_name}}.</a></li>
        {% endfor %}

    </ul>


{% else %}
    <h3>you don't have any movies</h3>

{% endif %}